name: Secretkey
 
on:
  workflow_dispatch
 
jobs:
  use_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Access secret
        run: |
          echo "The secret is: ${{ secrets.MY_SECRET_KEY }}"
